### ISSUE TITLE
Unsupported object type

### ISSUE THREAD

**Issue by ManuelGysin** [bozaro/git-lfs-migrate#1]
Hello

I get this error everytime I try to migrate:

```
main] INFO git.lfs.migrate.Main -   convert revision: a4425df8143f2ad7932c1aa1ae501f236c60fad8 -> 8fcd0a90d35487aeac22e0c75e78440b6d08d5d9 (1092/1103)
Exception in thread "main" java.lang.IllegalStateException: Unsupported object type: bdc67f81d37831df3451fca5c496202e8f7b7403 (org.eclipse.jgit.revwalk.RevTag)
	at git.lfs.migrate.GitConverter.lambda$convert$0(GitConverter.java:75)
	at git.lfs.migrate.GitConverter$$Lambda$1/293907205.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at git.lfs.migrate.GitConverter.convert(GitConverter.java:60)
	at git.lfs.migrate.Main.processRepository(Main.java:69)
	at git.lfs.migrate.Main.main(Main.java:46)
```

Thanks
Manuel

**Comment by ManuelGysin** [comment]
Nevermind, somehow I forget that the source is open.
Currently working on a solution.

**Comment by tskarman** [comment]
@ManuelGysin You are prob. stumbling over tags.

Have a look at this commit of one fork: https://github.com/ndrego/git-lfs-migrate/commit/1d1af961e3369509a3c2662439b072af71d2a0a0

I decided to simply drop the tags instead. Easy enough to re-add.

**Comment by bozaro** [comment]
I forgot about tags.
I will add tag convert support in some hours.

**Comment by ManuelGysin** [comment]
Thanks a lot! :)
