### ISSUE TITLE
JNI Exception: NoClassDefFoundError for ru/bozaro/gitlfs/client/auth/AuthProvider

### ISSUE THREAD

**Issue by sapanda** [bozaro/git-lfs-migrate#12]
Hi I'm trying to run the migration on my repository and am unfortunately getting the following error with the latest JDK (jdk1.8.0_92) on my Mac (10.11.3). Error occurs both when I download the precompiled jar or when I build myself. Thanks!

```
$ java -jar git-lfs-migrate.jar -s source.git -d dest.git -l <URL> "*.dae" "*.psd" "*.zip" "*.bin" "*.mov" "*.mp4" "*.mp3" "*.wav" "*.jpg" "*.png" "*.jpeg" "*.obj" "*.fbx" "*.pc2" "*.asset" "*.tif"

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: ru/bozaro/gitlfs/client/auth/AuthProvider
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: ru.bozaro.gitlfs.client.auth.AuthProvider
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by sapanda** [comment]
Ah nvm, looks like I need to run from the root folder of the repository. Previously I had just copied the jar file. But now I get 401 Unauthorized errors - not sure how to pass credentials via the commands.

**Comment by sapanda** [comment]
Ah nvm, looks like I need to run from the root folder of the repository. Previously I had just copied the jar file. Unfortunately now I get the following. I wonder if it's an issue with Gitlab, where I'm storing the large files.

Getting the following on repeat:
```
Jun 14, 2016 9:49:06 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://gitlab.com:443: Broken pipe
```

And after a long while, the following exception: 
```
Exception in thread "main" java.util.concurrent.ExecutionException: org.apache.http.client.ClientProtocolException
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at git.lfs.migrate.Main$HttpUploader.close(Main.java:359)
	at git.lfs.migrate.Main.processRepository(Main.java:155)
	at git.lfs.migrate.Main.main(Main.java:77)
Caused by: org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at ru.bozaro.gitlfs.client.internal.HttpClientExecutor.executeMethod(HttpClientExecutor.java:26)
	at ru.bozaro.gitlfs.client.Client.doRequest(Client.java:275)
	at ru.bozaro.gitlfs.client.Client.putObject(Client.java:238)
	at ru.bozaro.gitlfs.client.BatchUploader.lambda$objectTask$13(BatchUploader.java:66)
	at ru.bozaro.gitlfs.client.internal.BatchWorker.processObject(BatchWorker.java:262)
	at ru.bozaro.gitlfs.client.internal.BatchWorker.lambda$submitTask$3(BatchWorker.java:223)
	at ru.bozaro.gitlfs.client.internal.BatchWorker.executeInPool(BatchWorker.java:298)
	at ru.bozaro.gitlfs.client.internal.BatchWorker.access$400(BatchWorker.java:34)
	at ru.bozaro.gitlfs.client.internal.BatchWorker$1.run(BatchWorker.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:107)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	... 15 more
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:876)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:847)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:126)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:138)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:169)
	at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:115)
	at org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:146)
	at org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:158)
	at org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:237)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:122)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	... 17 more
```

**Comment by bozaro** [comment]
The first error occurs if there is not a `vendors/*.jar` near `git-lfs-migrate.jar`.

**Comment by bozaro** [comment]
`Broken pipe` error occurs on unexpectedly closed the connection. I have no idea for what reason this can happen. May be you can find more information in logs on GitLab side.

Now I can suggest:

 * Check are LFS working for you repository by playing with console `git lfs` tool;
 * Try to use HTTP instead of HTTPS;
 * Try convert repository locally without file uploading (without keys `--lfs` and `--git`) and upload files manually.

**Comment by sapanda** [comment]
Thanks for the info! I ended up using `bfg` last night and eventually got that to work.
