### ISSUE TITLE
Bitbucket LFS

### ISSUE THREAD

**Issue by pdf** [bozaro/git-lfs-migrate#13]
I'm trying this out with the Bitbucket LFS Beta released today, but having some trouble (UUIDs in the output have been sanitised):

```
java -jar ~/git-lfs-migrate.jar -s source.git -d dest.git -g git@bitbucket.org:user/repo.git --check-lfs 
[main] INFO git.lfs.migrate.Main - LFS server: Batch API request exception
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.net.URI from String value ("https://bitbucket.org/{}/{120898b2-99b3-40e2-932d-d9622b245ad4}/info/lfs"): not a valid textual representation, problem: Illegal character in path at index 22: https://bitbucket.org/{}/{120898b2-99b3-40e2-932d-d9622b245ad4}/info/lfs
 at [Source: [B@548a102f; line: 1, column: 267] (through reference chain: ru.bozaro.gitlfs.common.data.Link["href"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:923)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:136)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3788)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2872)
        at ru.bozaro.gitlfs.client.auth.ExternalAuthProvider.getAuthUncached(ExternalAuthProvider.java:84)
        at ru.bozaro.gitlfs.client.auth.CachedAuthProvider.getAuth(CachedAuthProvider.java:38)
        at ru.bozaro.gitlfs.client.Client.doWork(Client.java:248)
        at ru.bozaro.gitlfs.client.Client.postBatch(Client.java:118)
        at git.lfs.migrate.Main.checkLfsAuthenticate(Main.java:98)
        at git.lfs.migrate.Main.main(Main.java:68)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 22: https://bitbucket.org/{}/{120898b2-99b3-40e2-932d-d9622b245ad4}/info/lfs
        at java.net.URI.create(URI.java:852)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer$Std._deserialize(FromStringDeserializer.java:214)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:122)
        ... 14 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 22: https://bitbucket.org/{}/{120898b2-99b3-40e2-932d-d9622b245ad4}/info/lfs
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 16 more
[main] ERROR git.lfs.migrate.Main - LFS server: Invalid base URL
```

I also tried specifying the LFS URI (`-l https://user:password@bitbucket.org/user/repo.git/info/lfs`) instead of the git repo, but that produces a similar result, a little further down the stack:

```
java -jar ~/git-lfs-migrate.jar -s source.git -d dest.git -l https://user:pass@bitbucket.org/user/repo.git/info/lfs --check-lfs
[main] INFO git.lfs.migrate.Main - LFS server: Batch API request exception
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.net.URI from String value ("https://bitbucket.org/{}/{120898b2-99b3-40e2-932d-d9622b245ad4}/info/lfs/object/verify?upload_id=6ae885b3-6de4-458b-a770-b35e8ef0674a"): not a valid textual representation, problem: Illegal character in path at index 22: https://bitbucket.org/{}/{120898b2-99b3-40e2-932d-d9622b245ad4}/info/lfs/object/verify?upload_id=6ae885b3-6de4-458b-a770-b35e8ef0674a
 at [Source: org.apache.http.conn.EofSensorInputStream@29d89d5d; line: 1, column: 121] (through reference chain: ru.bozaro.gitlfs.common.data.BatchRes["objects"]->java.util.ArrayList[0]->ru.bozaro.gitlfs.common.data.BatchItem["actions"]->java.util.LinkedHashMap["verify"]->ru.bozaro.gitlfs.common.data.Link["href"])
        at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:74)
        at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:923)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:136)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:436)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:344)
        at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
        at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3788)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2849)
        at ru.bozaro.gitlfs.client.internal.JsonPost.processResponse(JsonPost.java:52)
        at ru.bozaro.gitlfs.client.Client.doRequest(Client.java:311)
        at ru.bozaro.gitlfs.client.Client.lambda$postBatch$7(Client.java:118)
        at ru.bozaro.gitlfs.client.Client.doWork(Client.java:252)
        at ru.bozaro.gitlfs.client.Client.postBatch(Client.java:118)
        at git.lfs.migrate.Main.checkLfsAuthenticate(Main.java:98)
        at git.lfs.migrate.Main.main(Main.java:68)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 22: https://bitbucket.org/{}/{120898b2-99b3-40e2-932d-d9622b245ad4}/info/lfs/object/verify?upload_id=6ae885b3-6de4-458b-a770-b35e8ef0674a
        at java.net.URI.create(URI.java:852)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer$Std._deserialize(FromStringDeserializer.java:214)
        at com.fasterxml.jackson.databind.deser.std.FromStringDeserializer.deserialize(FromStringDeserializer.java:122)
        ... 33 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 22: https://bitbucket.org/{}/{120898b2-99b3-40e2-932d-d9622b245ad4}/info/lfs/object/verify?upload_id=6ae885b3-6de4-458b-a770-b35e8ef0674a
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at java.net.URI.create(URI.java:850)
        ... 35 more
[main] ERROR git.lfs.migrate.Main - LFS server: Unsupported batch API
```

I'm not sure how the URI is constructed, but it's obviously barfing on the brackets `{` `}`, which are not encoded.  The repos do work using the standard `git-lfs` client, but it looks to me like perhaps some of the API responses from Bitbucket are not correctly populated - I suspect occurrences of `{}` are supposed to contain the user name, and occurrences of `{120898b2-99b3-40e2-932d-d9622b245ad4}` are supposed to contain the repo name, though I'm surprised that the standard client works if that's the case.  Thoughts?

**Comment by pdf** [comment]
FYI, Atlassian are looking at this internally also, I'll update here if they track this down to an API issue.

**Comment by sgoo** [comment]
Hi, I'm a developer on Bitbucket.
We have confirmed that this is an issue with our LFS implementation, we should be escaping `{}` as `%7B%7D`. A fix for this will hopefully be deployed in the next 24 hours.

**Comment by pdf** [comment]
Thanks @sgoo, I'll close this here then.  I do find it interesting that `git-lfs` works correctly with your current URIs, I suppose it must be URL-encoding the path before trying to call it.

**Comment by bozaro** [comment]
Unfortunately I am offline now. I will see this issue in two weeks.11:57, 19 июля 2016 г., Scott Goodhew <notifications@github.com>:Hi, I'm a developer on Bitbucket. We have confirmed that this is an issue with our LFS implementation, we should be escaping {} as %7B%7D. A fix for this will hopefully be deployed in the next 24 hours. —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.     Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
