### ISSUE TITLE
Exception in thread "main" java.util.concurrent.ExecutionException: ru.bozaro.gitlfs.client.exceptions.RequestException

### ISSUE THREAD

**Issue by kalibyrn** [bozaro/git-lfs-migrate#5]
I receive this stacktrace when using git-lfs-migrate 0.1.0:

```
Exception in thread "main" java.util.concurrent.ExecutionException: ru.bozaro.gitlfs.client.exceptions.RequestException
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at git.lfs.migrate.Main$HttpUploader.close(Main.java:292)
        at git.lfs.migrate.Main.processRepository(Main.java:88)
        at git.lfs.migrate.Main.main(Main.java:60)
Caused by: ru.bozaro.gitlfs.client.exceptions.RequestException
        at ru.bozaro.gitlfs.client.Client.doRequest(Client.java:314)
        at ru.bozaro.gitlfs.client.internal.BatchWorker.submitBatchTask(BatchWorker.java:162)
        at ru.bozaro.gitlfs.client.internal.BatchWorker.lambda$tryBatchRequest$0(BatchWorker.java:124)
        at ru.bozaro.gitlfs.client.internal.BatchWorker.executeInPool(BatchWorker.java:298)
        at ru.bozaro.gitlfs.client.internal.BatchWorker.access$400(BatchWorker.java:34)
        at ru.bozaro.gitlfs.client.internal.BatchWorker$1.run(BatchWorker.java:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

The command run was:

```
java -jar /mnt/tools/git-lfs-migrate.jar -t 16 -s lfs-test.git -d lfs-clean.git -l http://10.100.166.77:8081/artifactory/api/lfs/git-lfs .7z .CUR .EXE .NED .VSD .avi .bak .bz2 .chm .dll .dmp .doc .docx .dot .exe .git .gz .jar .jpg .jpi .mpp .msi .pdf .png .ppt .pptx .rar .vdx .vsd .war .xls .xlsm .xlsx .zip
```

**Comment by bozaro** [comment]
@kalibyrn What is you Artifactory version?

I can see some reason for this error:

 * Incorrect base URL: http://10.100.166.77:8081/artifactory/api/lfs/git-lfs
 * Artifactory may not support Git LFS Batch API (git-lfs-migrate don't tested with Artifactory)
 * Some bug somewhere

So, fo solve you problem:

 * I will add more detailed error information;
 * I will add git-lfs server check url/capability test on git-lfs-migrate startup.

**Comment by kalibyrn** [comment]
Great, thanks! I'm using the latest released trial version of Artifactory as of‎ last week. I believe it is 4.3, but I can check early in the week.

I can rerun your script with the debugging information and I'll let you know what I find.

From: Artem V. Navrotskiy
Sent: Saturday, November 28, 2015 4:47 AM
To: bozaro/git-lfs-migrate
Reply To: bozaro/git-lfs-migrate
Cc: Rob Duff
Subject: Re: [git-lfs-migrate] Exception in thread "main" java.util.concurrent.ExecutionException: ru.bozaro.gitlfs.client.exceptions.RequestException (#5)


@kalibyrn What is you Artifactory version?

I can see some reason for this error:

 * Incorrect base URL: http://10.100.166.77:8081/artifactory/api/lfs/git-lfs
 * Artifactory may not support Git LFS Batch API (git-lfs-migrate don't tested with Artifactory)
 * Some bug somewhere

So, fo solve you problem:

 * I will add more detailed error information;
 * I will add git-lfs server check url/capability test on git-lfs-migrate startup.

---

**Comment by bozaro** [comment]
I create branch with more verbose error messages and check LFS base URL on startup.

You can see binaries at page: https://builder.bozaro.ru/job/git-as-svn/branch/verbose/

Artifactory I don't check yet. But I can suggest to see GitLab 8.2 with embedded LFS server.
